/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddCustomerRequest {
  'customerName' : string,
  'gstNumber' : string,
  'address' : string,
  'companyName' : string,
  'openingBalance' : bigint,
  'mobile' : string,
}
export interface AddReceiptRequest {
  'customerName' : string,
  'date' : string,
  'paymentMode' : string,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export interface AddSaleRequest {
  'customerName' : string,
  'date' : string,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export interface Customer {
  'id' : CustomerId,
  'customerName' : string,
  'gstNumber' : string,
  'createdAt' : Timestamp,
  'address' : string,
  'companyName' : string,
  'openingBalance' : bigint,
  'mobile' : string,
  'customerCode' : string,
}
export type CustomerId = string;
export interface CustomerLedger {
  'customer' : Customer,
  'entries' : Array<MonthlyLedgerEntry>,
}
export interface CustomerSummary {
  'customerName' : string,
  'totalReceipts' : bigint,
  'gstNumber' : string,
  'totalSale' : bigint,
  'closingBalance' : bigint,
  'companyName' : string,
  'openingBalance' : bigint,
  'mobile' : string,
  'customerCode' : string,
}
export interface DashboardStats {
  'pendingPayments' : bigint,
  'totalReceipts' : bigint,
  'totalOutstanding' : bigint,
  'monthlyCollection' : bigint,
  'totalSales' : bigint,
  'totalCustomers' : bigint,
}
export interface MonthlyLedgerEntry {
  'month' : string,
  'sales' : bigint,
  'closingBalance' : bigint,
  'openingBalance' : bigint,
  'receipts' : bigint,
}
export interface Receipt {
  'id' : ReceiptId,
  'customerName' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'paymentMode' : string,
  'customerId' : CustomerId,
  'receiptNo' : string,
  'amount' : bigint,
}
export type ReceiptId = string;
export interface Sale {
  'id' : SaleId,
  'customerName' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'invoiceNo' : string,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export type SaleId = string;
export type Timestamp = bigint;
export interface UpdateCustomerRequest {
  'id' : CustomerId,
  'customerName' : string,
  'gstNumber' : string,
  'address' : string,
  'companyName' : string,
  'openingBalance' : bigint,
  'mobile' : string,
}
export interface UpdateReceiptRequest {
  'id' : ReceiptId,
  'customerName' : string,
  'date' : string,
  'paymentMode' : string,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export interface UpdateSaleRequest {
  'id' : SaleId,
  'customerName' : string,
  'date' : string,
  'customerId' : CustomerId,
  'amount' : bigint,
}
export interface _SERVICE {
  'addCustomer' : ActorMethod<[AddCustomerRequest], Customer>,
  'addReceipt' : ActorMethod<[AddReceiptRequest], Receipt>,
  'addSale' : ActorMethod<[AddSaleRequest], Sale>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllReceipts' : ActorMethod<[], Array<Receipt>>,
  'getAllSales' : ActorMethod<[], Array<Sale>>,
  'getCustomerById' : ActorMethod<[string], [] | [Customer]>,
  'getCustomerLedger' : ActorMethod<[string], [] | [CustomerLedger]>,
  'getCustomerSummaries' : ActorMethod<[], Array<CustomerSummary>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getReceiptsByCustomer' : ActorMethod<[string], Array<Receipt>>,
  'getSalesByCustomer' : ActorMethod<[string], Array<Sale>>,
  'updateCustomer' : ActorMethod<[UpdateCustomerRequest], [] | [Customer]>,
  'updateReceipt' : ActorMethod<[UpdateReceiptRequest], [] | [Receipt]>,
  'updateSale' : ActorMethod<[UpdateSaleRequest], [] | [Sale]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];