/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddCustomerRequest = IDL.Record({
  'customerName' : IDL.Text,
  'gstNumber' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'openingBalance' : IDL.Nat,
  'mobile' : IDL.Text,
});
export const CustomerId = IDL.Text;
export const Timestamp = IDL.Int;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'customerName' : IDL.Text,
  'gstNumber' : IDL.Text,
  'createdAt' : Timestamp,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'openingBalance' : IDL.Nat,
  'mobile' : IDL.Text,
  'customerCode' : IDL.Text,
});
export const AddReceiptRequest = IDL.Record({
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'paymentMode' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const ReceiptId = IDL.Text;
export const Receipt = IDL.Record({
  'id' : ReceiptId,
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'paymentMode' : IDL.Text,
  'customerId' : CustomerId,
  'receiptNo' : IDL.Text,
  'amount' : IDL.Nat,
});
export const AddSaleRequest = IDL.Record({
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const SaleId = IDL.Text;
export const Sale = IDL.Record({
  'id' : SaleId,
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'invoiceNo' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const MonthlyLedgerEntry = IDL.Record({
  'month' : IDL.Text,
  'sales' : IDL.Nat,
  'closingBalance' : IDL.Int,
  'openingBalance' : IDL.Int,
  'receipts' : IDL.Nat,
});
export const CustomerLedger = IDL.Record({
  'customer' : Customer,
  'entries' : IDL.Vec(MonthlyLedgerEntry),
});
export const CustomerSummary = IDL.Record({
  'customerName' : IDL.Text,
  'totalReceipts' : IDL.Nat,
  'gstNumber' : IDL.Text,
  'totalSale' : IDL.Nat,
  'closingBalance' : IDL.Int,
  'companyName' : IDL.Text,
  'openingBalance' : IDL.Nat,
  'mobile' : IDL.Text,
  'customerCode' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'pendingPayments' : IDL.Nat,
  'totalReceipts' : IDL.Nat,
  'totalOutstanding' : IDL.Int,
  'monthlyCollection' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const UpdateCustomerRequest = IDL.Record({
  'id' : CustomerId,
  'customerName' : IDL.Text,
  'gstNumber' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'openingBalance' : IDL.Nat,
  'mobile' : IDL.Text,
});
export const UpdateReceiptRequest = IDL.Record({
  'id' : ReceiptId,
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'paymentMode' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});
export const UpdateSaleRequest = IDL.Record({
  'id' : SaleId,
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([AddCustomerRequest], [Customer], []),
  'addReceipt' : IDL.Func([AddReceiptRequest], [Receipt], []),
  'addSale' : IDL.Func([AddSaleRequest], [Sale], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllReceipts' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getCustomerById' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getCustomerLedger' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomerLedger)],
      ['query'],
    ),
  'getCustomerSummaries' : IDL.Func([], [IDL.Vec(CustomerSummary)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getReceiptsByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Receipt)], ['query']),
  'getSalesByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Sale)], ['query']),
  'updateCustomer' : IDL.Func([UpdateCustomerRequest], [IDL.Opt(Customer)], []),
  'updateReceipt' : IDL.Func([UpdateReceiptRequest], [IDL.Opt(Receipt)], []),
  'updateSale' : IDL.Func([UpdateSaleRequest], [IDL.Opt(Sale)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddCustomerRequest = IDL.Record({
    'customerName' : IDL.Text,
    'gstNumber' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'openingBalance' : IDL.Nat,
    'mobile' : IDL.Text,
  });
  const CustomerId = IDL.Text;
  const Timestamp = IDL.Int;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'customerName' : IDL.Text,
    'gstNumber' : IDL.Text,
    'createdAt' : Timestamp,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'openingBalance' : IDL.Nat,
    'mobile' : IDL.Text,
    'customerCode' : IDL.Text,
  });
  const AddReceiptRequest = IDL.Record({
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'paymentMode' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const ReceiptId = IDL.Text;
  const Receipt = IDL.Record({
    'id' : ReceiptId,
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'paymentMode' : IDL.Text,
    'customerId' : CustomerId,
    'receiptNo' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const AddSaleRequest = IDL.Record({
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const SaleId = IDL.Text;
  const Sale = IDL.Record({
    'id' : SaleId,
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'invoiceNo' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const MonthlyLedgerEntry = IDL.Record({
    'month' : IDL.Text,
    'sales' : IDL.Nat,
    'closingBalance' : IDL.Int,
    'openingBalance' : IDL.Int,
    'receipts' : IDL.Nat,
  });
  const CustomerLedger = IDL.Record({
    'customer' : Customer,
    'entries' : IDL.Vec(MonthlyLedgerEntry),
  });
  const CustomerSummary = IDL.Record({
    'customerName' : IDL.Text,
    'totalReceipts' : IDL.Nat,
    'gstNumber' : IDL.Text,
    'totalSale' : IDL.Nat,
    'closingBalance' : IDL.Int,
    'companyName' : IDL.Text,
    'openingBalance' : IDL.Nat,
    'mobile' : IDL.Text,
    'customerCode' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'pendingPayments' : IDL.Nat,
    'totalReceipts' : IDL.Nat,
    'totalOutstanding' : IDL.Int,
    'monthlyCollection' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const UpdateCustomerRequest = IDL.Record({
    'id' : CustomerId,
    'customerName' : IDL.Text,
    'gstNumber' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'openingBalance' : IDL.Nat,
    'mobile' : IDL.Text,
  });
  const UpdateReceiptRequest = IDL.Record({
    'id' : ReceiptId,
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'paymentMode' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  const UpdateSaleRequest = IDL.Record({
    'id' : SaleId,
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([AddCustomerRequest], [Customer], []),
    'addReceipt' : IDL.Func([AddReceiptRequest], [Receipt], []),
    'addSale' : IDL.Func([AddSaleRequest], [Sale], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllReceipts' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getCustomerById' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getCustomerLedger' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerLedger)],
        ['query'],
      ),
    'getCustomerSummaries' : IDL.Func(
        [],
        [IDL.Vec(CustomerSummary)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getReceiptsByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Receipt)],
        ['query'],
      ),
    'getSalesByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Sale)], ['query']),
    'updateCustomer' : IDL.Func(
        [UpdateCustomerRequest],
        [IDL.Opt(Customer)],
        [],
      ),
    'updateReceipt' : IDL.Func([UpdateReceiptRequest], [IDL.Opt(Receipt)], []),
    'updateSale' : IDL.Func([UpdateSaleRequest], [IDL.Opt(Sale)], []),
  });
};

export const init = ({ IDL }) => { return []; };