/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AddCustomerRequest {
    customerName: string;
    gstNumber: string;
    address: string;
    companyName: string;
    openingBalance: bigint;
    mobile: string;
}
export type Timestamp = bigint;
export interface UpdateCustomerRequest {
    id: CustomerId;
    customerName: string;
    gstNumber: string;
    address: string;
    companyName: string;
    openingBalance: bigint;
    mobile: string;
}
export interface AddSaleRequest {
    customerName: string;
    date: string;
    customerId: CustomerId;
    amount: bigint;
}
export interface CustomerLedger {
    customer: Customer;
    entries: Array<MonthlyLedgerEntry>;
}
export interface AddReceiptRequest {
    customerName: string;
    date: string;
    paymentMode: string;
    customerId: CustomerId;
    amount: bigint;
}
export interface Sale {
    id: SaleId;
    customerName: string;
    date: string;
    createdAt: Timestamp;
    invoiceNo: string;
    customerId: CustomerId;
    amount: bigint;
}
export interface DashboardStats {
    pendingPayments: bigint;
    totalReceipts: bigint;
    totalOutstanding: bigint;
    monthlyCollection: bigint;
    totalSales: bigint;
    totalCustomers: bigint;
}
export interface Customer {
    id: CustomerId;
    customerName: string;
    gstNumber: string;
    createdAt: Timestamp;
    address: string;
    companyName: string;
    openingBalance: bigint;
    mobile: string;
    customerCode: string;
}
export type ReceiptId = string;
export interface MonthlyLedgerEntry {
    month: string;
    sales: bigint;
    closingBalance: bigint;
    openingBalance: bigint;
    receipts: bigint;
}
export interface Receipt {
    id: ReceiptId;
    customerName: string;
    date: string;
    createdAt: Timestamp;
    paymentMode: string;
    customerId: CustomerId;
    receiptNo: string;
    amount: bigint;
}
export interface UpdateSaleRequest {
    id: SaleId;
    customerName: string;
    date: string;
    customerId: CustomerId;
    amount: bigint;
}
export type CustomerId = string;
export type SaleId = string;
export interface CustomerSummary {
    customerName: string;
    totalReceipts: bigint;
    gstNumber: string;
    totalSale: bigint;
    closingBalance: bigint;
    companyName: string;
    openingBalance: bigint;
    mobile: string;
    customerCode: string;
}
export interface UpdateReceiptRequest {
    id: ReceiptId;
    customerName: string;
    date: string;
    paymentMode: string;
    customerId: CustomerId;
    amount: bigint;
}
export interface backendInterface {
    addCustomer(req: AddCustomerRequest): Promise<Customer>;
    addReceipt(req: AddReceiptRequest): Promise<Receipt>;
    addSale(req: AddSaleRequest): Promise<Sale>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllReceipts(): Promise<Array<Receipt>>;
    getAllSales(): Promise<Array<Sale>>;
    getCustomerById(id: string): Promise<Customer | null>;
    getCustomerLedger(customerId: string): Promise<CustomerLedger | null>;
    getCustomerSummaries(): Promise<Array<CustomerSummary>>;
    getDashboardStats(): Promise<DashboardStats>;
    getReceiptsByCustomer(customerId: string): Promise<Array<Receipt>>;
    getSalesByCustomer(customerId: string): Promise<Array<Sale>>;
    updateCustomer(req: UpdateCustomerRequest): Promise<Customer | null>;
    updateReceipt(req: UpdateReceiptRequest): Promise<Receipt | null>;
    updateSale(req: UpdateSaleRequest): Promise<Sale | null>;
}
import type { Customer as _Customer, CustomerLedger as _CustomerLedger, Receipt as _Receipt, Sale as _Sale } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: AddCustomerRequest): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async addReceipt(arg0: AddReceiptRequest): Promise<Receipt> {
        if (this.processError) {
            try {
                const result = await this.actor.addReceipt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReceipt(arg0);
            return result;
        }
    }
    async addSale(arg0: AddSaleRequest): Promise<Sale> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllReceipts(): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReceipts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReceipts();
            return result;
        }
    }
    async getAllSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSales();
            return result;
        }
    }
    async getCustomerById(arg0: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerById(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerById(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerLedger(arg0: string): Promise<CustomerLedger | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerLedger(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerLedger(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerSummaries(): Promise<Array<CustomerSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerSummaries();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getReceiptsByCustomer(arg0: string): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceiptsByCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceiptsByCustomer(arg0);
            return result;
        }
    }
    async getSalesByCustomer(arg0: string): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesByCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesByCustomer(arg0);
            return result;
        }
    }
    async updateCustomer(arg0: UpdateCustomerRequest): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateReceipt(arg0: UpdateReceiptRequest): Promise<Receipt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReceipt(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReceipt(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSale(arg0: UpdateSaleRequest): Promise<Sale | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSale(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSale(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerLedger]): CustomerLedger | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Receipt]): Receipt | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sale]): Sale | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
