/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute } from "@tanstack/react-router";

import { Route as rootRoute } from "./routes/__root";
import { Route as CustomersIdImport } from "./routes/customers/$id";
import { Route as CustomersIdEditImport } from "./routes/customers/$id.edit";
import { Route as CustomersAddImport } from "./routes/customers/add";
import { Route as CustomersImport } from "./routes/customers/index";
import { Route as IndexImport } from "./routes/index";
import { Route as ReceiptsIdImport } from "./routes/receipts/$id";
import { Route as ReceiptsIdEditImport } from "./routes/receipts/$id.edit";
import { Route as ReceiptsAddImport } from "./routes/receipts/add";
import { Route as ReceiptsImport } from "./routes/receipts/index";
import { Route as SalesIdImport } from "./routes/sales/$id";
import { Route as SalesIdEditImport } from "./routes/sales/$id.edit";
import { Route as SalesAddImport } from "./routes/sales/add";
import { Route as SalesImport } from "./routes/sales/index";

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const CustomersRoute = CustomersImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => rootRoute,
} as any);

const CustomersAddRoute = CustomersAddImport.update({
  id: "/customers/add",
  path: "/customers/add",
  getParentRoute: () => rootRoute,
} as any);

const CustomersIdRoute = CustomersIdImport.update({
  id: "/customers/$id",
  path: "/customers/$id",
  getParentRoute: () => rootRoute,
} as any);

const CustomersIdEditRoute = CustomersIdEditImport.update({
  id: "/customers/$id/edit",
  path: "/customers/$id/edit",
  getParentRoute: () => rootRoute,
} as any);

const SalesRoute = SalesImport.update({
  id: "/sales",
  path: "/sales",
  getParentRoute: () => rootRoute,
} as any);

const SalesAddRoute = SalesAddImport.update({
  id: "/sales/add",
  path: "/sales/add",
  getParentRoute: () => rootRoute,
} as any);

const SalesIdRoute = SalesIdImport.update({
  id: "/sales/$id",
  path: "/sales/$id",
  getParentRoute: () => rootRoute,
} as any);

const SalesIdEditRoute = SalesIdEditImport.update({
  id: "/sales/$id/edit",
  path: "/sales/$id/edit",
  getParentRoute: () => rootRoute,
} as any);

const ReceiptsRoute = ReceiptsImport.update({
  id: "/receipts",
  path: "/receipts",
  getParentRoute: () => rootRoute,
} as any);

const ReceiptsAddRoute = ReceiptsAddImport.update({
  id: "/receipts/add",
  path: "/receipts/add",
  getParentRoute: () => rootRoute,
} as any);

const ReceiptsIdRoute = ReceiptsIdImport.update({
  id: "/receipts/$id",
  path: "/receipts/$id",
  getParentRoute: () => rootRoute,
} as any);

const ReceiptsIdEditRoute = ReceiptsIdEditImport.update({
  id: "/receipts/$id/edit",
  path: "/receipts/$id/edit",
  getParentRoute: () => rootRoute,
} as any);

export interface FileRoutesByPath {
  "/": {
    id: "/";
    path: "/";
    fullPath: "/";
    preLoaderRoute: typeof IndexImport;
    parentRoute: typeof rootRoute;
  };
  "/customers": {
    id: "/customers";
    path: "/customers";
    fullPath: "/customers";
    preLoaderRoute: typeof CustomersImport;
    parentRoute: typeof rootRoute;
  };
  "/customers/add": {
    id: "/customers/add";
    path: "/customers/add";
    fullPath: "/customers/add";
    preLoaderRoute: typeof CustomersAddImport;
    parentRoute: typeof rootRoute;
  };
  "/customers/$id": {
    id: "/customers/$id";
    path: "/customers/$id";
    fullPath: "/customers/$id";
    preLoaderRoute: typeof CustomersIdImport;
    parentRoute: typeof rootRoute;
  };
  "/customers/$id/edit": {
    id: "/customers/$id/edit";
    path: "/customers/$id/edit";
    fullPath: "/customers/$id/edit";
    preLoaderRoute: typeof CustomersIdEditImport;
    parentRoute: typeof rootRoute;
  };
  "/sales": {
    id: "/sales";
    path: "/sales";
    fullPath: "/sales";
    preLoaderRoute: typeof SalesImport;
    parentRoute: typeof rootRoute;
  };
  "/sales/add": {
    id: "/sales/add";
    path: "/sales/add";
    fullPath: "/sales/add";
    preLoaderRoute: typeof SalesAddImport;
    parentRoute: typeof rootRoute;
  };
  "/sales/$id": {
    id: "/sales/$id";
    path: "/sales/$id";
    fullPath: "/sales/$id";
    preLoaderRoute: typeof SalesIdImport;
    parentRoute: typeof rootRoute;
  };
  "/sales/$id/edit": {
    id: "/sales/$id/edit";
    path: "/sales/$id/edit";
    fullPath: "/sales/$id/edit";
    preLoaderRoute: typeof SalesIdEditImport;
    parentRoute: typeof rootRoute;
  };
  "/receipts": {
    id: "/receipts";
    path: "/receipts";
    fullPath: "/receipts";
    preLoaderRoute: typeof ReceiptsImport;
    parentRoute: typeof rootRoute;
  };
  "/receipts/add": {
    id: "/receipts/add";
    path: "/receipts/add";
    fullPath: "/receipts/add";
    preLoaderRoute: typeof ReceiptsAddImport;
    parentRoute: typeof rootRoute;
  };
  "/receipts/$id": {
    id: "/receipts/$id";
    path: "/receipts/$id";
    fullPath: "/receipts/$id";
    preLoaderRoute: typeof ReceiptsIdImport;
    parentRoute: typeof rootRoute;
  };
  "/receipts/$id/edit": {
    id: "/receipts/$id/edit";
    path: "/receipts/$id/edit";
    fullPath: "/receipts/$id/edit";
    preLoaderRoute: typeof ReceiptsIdEditImport;
    parentRoute: typeof rootRoute;
  };
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CustomersRoute,
  CustomersAddRoute,
  CustomersIdEditRoute,
  CustomersIdRoute,
  SalesRoute,
  SalesAddRoute,
  SalesIdEditRoute,
  SalesIdRoute,
  ReceiptsRoute,
  ReceiptsAddRoute,
  ReceiptsIdEditRoute,
  ReceiptsIdRoute,
]);

/* prettier-ignore-end */
